name: tasawoqi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_map: ^8.2.1
  flutter_otp_text_field: ^1.5.1+1
  flutter_svg: ^2.1.6
  get: ^4.6.5
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/json/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
